# Generated by Django 4.2.7 on 2025-10-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "author_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("pen_name", models.CharField(max_length=50, unique=True)),
                ("intro", models.TextField(blank=True)),
                ("identity_status", models.SmallIntegerField(default=0)),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("parent_id", models.IntegerField(blank=True, null=True)),
                ("sort_num", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("chapter_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("work_id", models.BigIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("word_count", models.IntegerField()),
                ("is_free", models.SmallIntegerField(default=1)),
                ("sort_num", models.IntegerField()),
                ("status", models.SmallIntegerField(default=0)),
                ("publish_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "chapters",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reader_id", models.BigIntegerField()),
                ("work_id", models.BigIntegerField()),
                ("chapter_id", models.BigIntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                ("parent_id", models.BigIntegerField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.SmallIntegerField(default=1)),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "editor_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("real_name", models.CharField(max_length=50)),
                ("department", models.CharField(blank=True, max_length=50)),
                ("position", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "editors",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sender_id", models.BigIntegerField(blank=True, null=True)),
                ("recipient_id", models.BigIntegerField()),
                ("message_type", models.SmallIntegerField()),
                ("content", models.TextField()),
                ("related_type", models.SmallIntegerField(blank=True, null=True)),
                ("related_id", models.BigIntegerField(blank=True, null=True)),
                ("is_read", models.SmallIntegerField(default=0)),
                ("send_time", models.DateTimeField(auto_now_add=True)),
                ("expire_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "messages",
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                ("ranking_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("category_id", models.IntegerField(blank=True, null=True)),
                ("period", models.SmallIntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("source_type", models.JSONField()),
                ("status", models.SmallIntegerField(default=1)),
                ("sort_rule", models.CharField(default="score DESC", max_length=50)),
                ("display_limit", models.IntegerField(default=100)),
            ],
            options={
                "db_table": "rankings",
            },
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "reader_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("nickname", models.CharField(max_length=50)),
                ("avatar_url", models.CharField(blank=True, max_length=500)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "readers",
            },
        ),
        migrations.CreateModel(
            name="ReadingRecord",
            fields=[
                ("record_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reader_id", models.BigIntegerField()),
                ("chapter_id", models.BigIntegerField()),
                ("read_time", models.DateTimeField(auto_now_add=True)),
                ("progress", models.IntegerField(default=0)),
                ("is_finished", models.SmallIntegerField(default=0)),
            ],
            options={
                "db_table": "reading_records",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("sub_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reader_id", models.BigIntegerField()),
                ("work_id", models.BigIntegerField()),
                ("chapter_id", models.BigIntegerField(blank=True, null=True)),
                ("sub_time", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("role", models.SmallIntegerField()),
                ("status", models.SmallIntegerField(default=1)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("last_login_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                ("work_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author_id", models.BigIntegerField()),
                ("category_id", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("cover_url", models.CharField(blank=True, max_length=500)),
                ("intro", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("status", models.SmallIntegerField(default=0)),
                ("is_signed", models.SmallIntegerField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "works",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("vote_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("reader_id", models.BigIntegerField()),
                ("work_id", models.BigIntegerField()),
                ("vote_type", models.SmallIntegerField()),
                ("vote_time", models.DateField()),
                ("count", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "votes",
                "unique_together": {("reader_id", "work_id", "vote_type", "vote_time")},
            },
        ),
        migrations.CreateModel(
            name="RankingDetail",
            fields=[
                ("detail_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ranking_id", models.IntegerField()),
                ("work_id", models.BigIntegerField()),
                ("stat_date", models.DateField()),
                ("rank", models.IntegerField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source_data", models.JSONField()),
            ],
            options={
                "db_table": "ranking_details",
                "unique_together": {("ranking_id", "work_id", "stat_date")},
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "collection_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("reader_id", models.BigIntegerField()),
                ("work_id", models.BigIntegerField()),
                ("collect_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "collections",
                "unique_together": {("reader_id", "work_id")},
            },
        ),
    ]
