# Generated by Django 4.2.7 on 2025-11-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=models.CASCADE, primary_key=True, serialize=False, to='novel_platform.user')),
                ('can_publish', models.SmallIntegerField(default=1)),
                ('can_subscribe', models.SmallIntegerField(default=1)),
                ('can_recharge', models.SmallIntegerField(default=1)),
                ('can_comment', models.SmallIntegerField(default=1)),
                ('can_vote', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.CreateModel(
            name='WorkModeration',
            fields=[
                ('work', models.OneToOneField(db_column='work_id', on_delete=models.CASCADE, primary_key=True, serialize=False, to='novel_platform.work')),
                ('is_hidden', models.SmallIntegerField(default=0)),
                ('chapters_blocked', models.SmallIntegerField(default=0)),
                ('updates_blocked', models.SmallIntegerField(default=0)),
                ('subscriptions_blocked', models.SmallIntegerField(default=0)),
                ('votes_blocked', models.SmallIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'work_moderations',
            },
        ),
    ]




