# Generated by Django 4.2.7 on 2025-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_platform', '0002_admin_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_id', models.BigIntegerField()),
                ('target_type', models.SmallIntegerField()),
                ('target_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_action_logs',
            },
        ),
    ]




